@startuml
skinparam componentStyle rectangle
left to right direction
'top to bottom direction
package "Local Storage" {

  [Новые данные] as ND
  [Pronation] as NDP
  [Изображения] as NDPFoto
  [Overpronation] as NDO
  [Изображения] as NDOFoto
  [Данные] as D
  [Pronation] as DP
  [Изображения] as DPFoto
  [Overpronation] as DO
  [Изображения] as DOFoto
  [Dataset] as DD
  [Data (pkl)] as DDD
  [Labals (pkl)] as DDL
  [Резерв данных] as DVC
  [DataTimeZip] as DTZ
  [Dataset] as ZDS
  [Data (pkl)] as ZDD
  [Label (pkl)] as ZDL
  [Overpronation] as ZO
  [Изображения] as ZOFoto
  [Pronation] as ZP
  [Изображения] as ZPFoto

  NDP --> NDPFoto
  ND --> NDO

  NDO --> NDOFoto
  ND --> NDP

  D <-- ND
  D --> DVC
  D --> DP
  D --> DO
  D --> DD

  DP --> DPFoto
  DO --> DOFoto
  DD --> DDD
  DD --> DDL

  DVC --> DTZ

  DTZ --> ZDS
  DTZ --> ZP
  DTZ --> ZO

  ZDS --> ZDD
  ZDS --> ZDL

  ZP --> ZPFoto
  ZO --> ZOFoto


}

@enduml