@startuml
!define ENTITY class
!define DATABASE class

package "Веб Приложение" {

    [Клиент]
    [Событие]
    [Обработчик событий]
    [Вывод результата]

}


package "Сервер" {

    package "Базы Данных" {


        package "Менеджер Файлов" {

        [Хранение]
        [Доступ]
        [Безопасность]


        }

        package "Обработчик данных" {

        [Обработка]

        }

        package "Аугментация данных" {

        [Аугментация входных данных]
        [Метод 1]
        [Метод 2]
        [Метод 3]
        [Метод и так далее]
        [Аугментированные данные]

        }
    }

    package "Модели" {

        [Модель 1]
        [Модель 2]
        [Модель 3]
        [Результат]

    }


}
[Клиент] --> [Событие]
[Событие] --> [Обработчик событий]
[Обработчик событий] --> [Обработка]
[Обработка] --> [Хранение]
[Обработка] --> [Аугментация входных данных]
[Аугментация входных данных] --> [Метод 1]
[Метод 1] --> [Метод 2]
[Метод 2] --> [Метод 3]
[Метод 3] --> [Метод и так далее]
[Метод и так далее] --> [Аугментированные данные]
[Аугментированные данные] --> [Хранение]
[Обработка] --> [Модель 1]
[Модель 1] --> [Модель 2]
[Модель 2] --> [Модель 3]
[Модель 3] --> [Результат]
[Результат] --> [Вывод результата]
@enduml
